spring:
  data:
    mongodb:
      authentication-database: admin
      database: amazon
      port: 27017
      host: localhost
token:
  signing:
    key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855

caching:
  spring:
    reportTTL: 120000